FROM node:18-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY packages ./packages
COPY apps/frontend ./apps/frontend

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/frontend

EXPOSE 3000

CMD ["pnpm", "dev", "--host"]